[package]
name = "rust_uuid"
version = "0.1.0"
authors = ["katsyoshi <github@katsyoshi.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rb-sys = "0.9"
rb-allocator = "0.9"
magnus = "0.6"

[dependencies.uuid]
version = "1.8"
features = [
  "v4",
  # "fast-rng",
]
